adress: http://localhost:8080/api
spring:
  thymeleaf:
    enabled: false

joinfaces:
  primefaces:
    theme: bootstrap

server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
